FROM node:22

RUN npm config --global set fund false
RUN npm config --global set update-notifier false
RUN npm install --global nodemon

WORKDIR /opt/client

COPY ./client/package.json .
COPY ./client/package-lock.json .
RUN npm install

COPY ./client .

CMD npm run dev
