# quick test routes

@baseUrl = https://localhost

###
# service version 
GET {{baseUrl}}/auth/version

###
# service status
GET {{baseUrl}}/auth/_up

###
# local login
POST {{baseUrl}}/auth/local/login
Content-Type: application/json

{
    "name": "{{$dotenv ADMIN_USER}}",
    "password": "{{$dotenv ADMIN_PASSWORD}}"
}

###
# check user's session (and generate a new token)
GET {{baseUrl}}/auth/session

###
# logout current users/session
POST {{baseUrl}}/auth/logout
Content-Type: application/json
