# quick test routes

@baseUrl = https://localhost

###
# service version 
GET {{baseUrl}}/api/version

###
# service status
GET {{baseUrl}}/api/_up

###
# local login
POST {{baseUrl}}/auth/local/login
Content-Type: application/json

{
    "name": "{{$dotenv ADMIN_USER}}",
    "password": "{{$dotenv ADMIN_PASSWORD}}"
}

###
# check user's session (and generate a new token)
# @name session
GET {{baseUrl}}/auth/session

###
# api tests here...
GET {{baseUrl}}/api/secret
Authorization: token {{session.response.body.token}}

###
# logout current users/session
POST {{baseUrl}}/auth/logout
Content-Type: application/json
